package com.careerpilot.backend.modules.application.domain;
public enum WorkflowState { DISCOVERED, MATCHED, ELIGIBLE, READY, WAITING_APPROVAL, APPROVED, REJECTED, SUBMITTING, SUBMITTED, FAILED, RETRYING, TRACKING, INTERVIEW, OFFER, REJECTED_BY_COMPANY, WITHDRAWN, COMPLETED, ARCHIVED }
