# One-time local setup for running CareerPilot WITHOUT Docker on Windows.
#   powershell -ExecutionPolicy Bypass -File scripts\local\setup.ps1
# Installs nothing system-wide: everything goes to %LOCALAPPDATA%\careerpilot.
param([switch]$SkipFrontend)
. (Join-Path $PSScriptRoot 'common.ps1')
New-Item -ItemType Directory -Force -Path $CpHome, $LogDir | Out-Null

Write-Host '== Checking prerequisites'
$javaVersion = (& java -version 2>&1 | ForEach-Object { "$_" } | Select-Object -First 1)
if ("$javaVersion" -notmatch '"21') { throw "Java 21 is required (found: $javaVersion)" }
$nodeVersion = (& node -v)
if ([int]($nodeVersion.TrimStart('v').Split('.')[0]) -lt 20) { throw "Node.js 20+ is required (found: $nodeVersion)" }
$python = Find-Python
if (-not (Get-Command ollama -ErrorAction SilentlyContinue)) {
    Write-Warning 'Ollama is not installed. Install it from https://ollama.com or configure a cloud LLM in .env.local.'
} else {
    $models = (& ollama list) -join "`n"
    foreach ($m in @('llama3.2', 'nomic-embed-text')) {
        if ($models -notmatch [regex]::Escape($m)) { Write-Host "Pulling Ollama model $m"; & ollama pull $m }
    }
}

Write-Host '== Secrets (.env.local)'
if (-not (Test-Path $EnvFile)) {
    $dbPassword = (New-Secret 24) -replace '[^A-Za-z0-9]', ''
    $keyBytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($keyBytes)
    @(
        '# Local secrets generated by scripts\local\setup.ps1 (git-ignored). Edit to switch AI providers.',
        "JWT_SECRET_KEY=$(New-Secret 48)",
        "AI_SERVICE_TOKEN=$((New-Secret 32) -replace '[^A-Za-z0-9]', '')",
        'DB_HOST=localhost', 'DB_PORT=5432', 'DB_NAME=careerpilot', 'DB_USER=careerpilot',
        "DB_PASSWORD=$dbPassword",
        "EMAIL_TOKEN_ENCRYPTION_KEY=$([Convert]::ToBase64String($keyBytes))",
        'LLM_PROVIDER=ollama', 'LLM_MODEL=', 'OLLAMA_BASE_URL=http://localhost:11434',
        'EMBEDDING_PROVIDER=ollama', 'EMBEDDING_MODEL=',
        'OPENAI_API_KEY=', 'ANTHROPIC_API_KEY=', 'GEMINI_API_KEY=',
        'CAREERPILOT_AI_TIMEOUT_MS=660000'
    ) | Set-Content -Path $EnvFile -Encoding ASCII
    Write-Host "Created $EnvFile"
}
Import-EnvFile

Write-Host '== PostgreSQL 16 (portable)'
if (-not (Test-Path (Join-Path $PgBin 'pg_ctl.exe'))) {
    $zip = Join-Path $CpHome 'pg16.zip'
    Invoke-WebRequest -UseBasicParsing -Uri 'https://get.enterprisedb.com/postgresql/postgresql-16.10-1-windows-x64-binaries.zip' -OutFile $zip
    Expand-Archive -Path $zip -DestinationPath $CpHome -Force
    Remove-Item $zip
}
if (-not (Test-Path (Join-Path $PgData 'PG_VERSION'))) {
    $pwFile = Join-Path $CpHome 'pg-superuser.pw'
    (New-Secret 24) | Set-Content -Path $pwFile -Encoding ASCII -NoNewline
    & (Join-Path $PgBin 'initdb.exe') -D $PgData -U postgres --pwfile=$pwFile -E UTF8 -A scram-sha-256 | Out-Null
    Assert-Exit 'initdb'
    Write-Host "Initialised database cluster at $PgData (superuser password in $pwFile)"
}
if (-not (Test-PortOpen 5432)) {
    Start-PostgresServer
}
$env:PGPASSWORD = Get-Content (Join-Path $CpHome 'pg-superuser.pw')
$psql = Join-Path $PgBin 'psql.exe'
$exists = & $psql -U postgres -h localhost -tAc "SELECT 1 FROM pg_roles WHERE rolname='$env:DB_USER'"
Assert-Exit 'Connecting to PostgreSQL'
if ($exists -ne '1') { & $psql -U postgres -h localhost -c "CREATE ROLE $env:DB_USER LOGIN PASSWORD '$env:DB_PASSWORD'" | Out-Null; Assert-Exit 'CREATE ROLE' }
$dbExists = & $psql -U postgres -h localhost -tAc "SELECT 1 FROM pg_database WHERE datname='$env:DB_NAME'"
if ($dbExists -ne '1') { & $psql -U postgres -h localhost -c "CREATE DATABASE $env:DB_NAME OWNER $env:DB_USER" | Out-Null; Assert-Exit 'CREATE DATABASE' }
Remove-Item Env:PGPASSWORD

Write-Host '== AI service Python environment'
if (-not (Test-Path (Join-Path $VenvDir 'Scripts\python.exe'))) {
    & $python[0] $python[1] -m venv $VenvDir
}
& (Join-Path $VenvDir 'Scripts\python.exe') -m pip install --quiet --upgrade pip
& (Join-Path $VenvDir 'Scripts\python.exe') -m pip install --quiet -r (Join-Path $RepoRoot 'apps\ai-service\requirements-dev.txt')

if (-not $SkipFrontend) {
    Write-Host '== Frontend dependencies'
    Push-Location (Join-Path $RepoRoot 'apps\frontend')
    & npm ci --no-audit --no-fund
    Assert-Exit 'npm ci'
    Pop-Location
}

Write-Host '== Backend build (Gradle 8.9 wrapper)'
$env:CAREERPILOT_BUILD_ROOT = $BuildRoot
Push-Location $RepoRoot
& .\gradlew.bat :apps:backend:bootJar -x test --console=plain -q
$gradleExit = $LASTEXITCODE
Pop-Location
if ($gradleExit -ne 0) { throw 'Backend build failed' }
if (-not (Test-Path $BackendJar)) { throw "Backend jar was not produced at $BackendJar" }

Write-Host ''
Write-Host 'Setup complete. Start everything with:  powershell -ExecutionPolicy Bypass -File scripts\local\start.ps1'
