package com.careerpilot.backend.modules.copilot.domain;

public enum CopilotIntent {
    JOB_SEARCH,
    COMPANY_SEARCH,
    RESUME_REVIEW,
    MATCH_EXPLANATION,
    GAP_ANALYSIS,
    INTERVIEW_PREPARATION,
    APPLICATION_STATUS,
    LEARNING_RECOMMENDATION,
    CAREER_PLANNING,
    DASHBOARD_SUMMARY,
    GENERAL_HELP
}
